Description: >
  OpenVPN SSM run documents

Resources:

  DockstoreVpnSSMCommandDocCreateMFA:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: "2.2"
        description: "Create a new VPN user with MFA enabled"
        parameters:
          Username:
            type: "String"
            description: "Username of the VPN user that will be created"
          Email:
            type: "String"
            description: "Email address to send the new user a link to their VPN and MFA files"
        mainSteps:
        - action: "aws:runShellScript"
          name: "createuser"
          inputs:
            runCommand:
              - "export MFA_DISABLED=''; cd /opt/easy-rsa && /opt/easy-rsa/gen_client.sh {{Username}}"
        - action: "aws:runShellScript"
          name: "emailuser"
          inputs:
            runCommand:
              - "export MFA_DISABLED=''; cd /opt/easy-rsa && /opt/easy-rsa/email_presigned_url.sh {{Username}} {{Email}}"
      DocumentType: Command
      Name: VPN-Create-Client-MFA
      Tags:
        - Key: Name
          Value: !Sub '${VpcName}-ssm-cmd-doc-gen-client-mfa'
        - Key: Owner
          Value: !Sub '${VpnOwner}'

  DockstoreVpnSSMCommandDocCreateHeadless:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: "2.2"
        description: "Create a new VPN user with MFA disabled"
        parameters:
          Username:
            type: "String"
            description: "Username of the VPN user that will be created"
          Email:
            type: "String"
            description: "Email address to send the new user a link to their VPN files"
        mainSteps:
        - action: "aws:runShellScript"
          name: "createuser"
          inputs:
            runCommand:
              - "export MFA_DISABLED='true'; cd /opt/easy-rsa/; /opt/easy-rsa/gen_client.sh {{Username}}"
        - action: "aws:runShellScript"
          name: "emailuser"
          inputs:
            runCommand:
              - "export MFA_DISABLED='true'; cd /opt/easy-rsa; /opt/easy-rsa/email_presigned_url.sh {{Username}} {{Email}}"
      DocumentType: Command
      Name: VPN-Create-Client-Headless
      Tags:
        - Key: Name
          Value: !Sub '${VpcName}-ssm-cmd-doc-gen-client-headless'
        - Key: Owner
          Value: !Sub '${VpnOwner}'

  DockstoreVpnSSMCommandDocDelete:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: "2.2"
        description: "Delete a VPN client"
        parameters:
          Username:
            type: "String"
            description: "Username of the VPN user that will be deleted"
        mainSteps:
        - action: "aws:runShellScript"
          name: "deleteuser"
          inputs:
            runCommand:
              - "cd /opt/easy-rsa; /opt/easy-rsa/del_client.sh {{Username}}"
      DocumentType: Command
      Name: VPN-Delete-Client
      Tags:
        - Key: Name
          Value: !Sub '${VpcName}-ssm-cmd-doc-del-client'
        - Key: Owner
          Value: !Sub '${VpnOwner}'
